### ISSUE TITLE
Make +/- work like a unary function (see line 77 in ViewController.swift)

### ISSUE THREAD

**Issue by blacksantorum** [buihdk/Calculator#2]
See extra credit description #3:

"3. Add a ᐩ/- operation which changes the sign of the number in the display. Be careful
with this one. If the user is in the middle of entering a number, you probably want to
change the sign of that number and allow typing to continue, not force an enter like
other operations do. On the other hand, **if the user is not in the middle of typing a
number, then this operation would work just like any other unary operation (e.g. cos).** "

**Comment by buihdk** [comment]
Fixed.
